name: Action Test

on: [push, pull_request]

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      persist-credentials: false
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Checkout main branch
        run: |
          git checkout main

      - name: Commit
        run: |
          git config --local user.email "yundabal@gmail.com"
          git config --local user.name "yundabal"
          set +e
          git add CHANGELOG.md
          git commit -m "Update changelog"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: ${{ github.ref }}